
export interface FAQ {
  id: number;
  question: string;
  answer: string;
}

const faqData: FAQ[] = [
  {
    id: 1,
    question: "What file types can I upload to Cognify?",
    answer: "Cognify supports multiple file formats including PDF documents, plain text files (.txt), and Microsoft Word documents (.docx). Simply drag and drop your learning material or click to browse, and our AI will process it to extract key themes and generate personalized lessons."
  },
  {
    id: 2,
    question: "How does the AI extract themes from my materials?",
    answer: "Our advanced AI analyzes your uploaded content to identify 3-7 main themes that are most relevant for workplace learning. The system examines the structure, key concepts, and relationships within your material to surface the most important topics that will help you upskill effectively."
  },
  {
    id: 3,
    question: "What makes Cognify lessons workplace-focused?",
    answer: "Every lesson generated by Cognify is tailored for professional development. We create concise 250-400 word summaries that highlight practical applications, key takeaways you can implement at work, and real-world context. Each lesson includes voice narration so you can learn on the go."
  },
  {
    id: 4,
    question: "Can I access my previous lessons and materials?",
    answer: "Absolutely! All your uploaded materials, extracted themes, and generated lessons are securely stored in our database. Each ingestion is tracked with a unique ID, making it easy to retrieve and reference your learning materials anytime you need them."
  },
  {
    id: 5,
    question: "How accurate are the AI-generated summaries?",
    answer: "Cognify includes citation references to the original source material, showing you the top 2-3 snippets that informed each lesson. This ensures transparency and allows you to verify the accuracy of the content while maintaining traceability back to your original documents."
  },
  {
    id: 6,
    question: "Is there a limit to how much content I can upload?",
    answer: "You can upload documents of various sizes, though we recommend keeping individual files under 10MB for optimal processing speed. There's no limit to the number of documents you can process - build your entire learning library with Cognify."
  }
];


export default faqData;
